'use client'; 

import { useState } from 'react';
import { useRouter } from 'next/navigation'; // Handles page routing
import { supabase } from '@/lib/supabaseClient'; 

export default function OnboardingStepOne() {
  const router = useRouter();
  const [companyName, setCompanyName] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');

    const payload = { user_age: 25 }; // id is auto-generated by identity, created_at defaults to now()
    console.log("Sending payload to 'users' table:", payload);

    // 1. Insert data into your specific Supabase table
    const { data, error } = await supabase
      .from('users')
      .insert([payload])
      .select();
    
    setLoading(false);

    if (error) {
      console.error("Supabase database error:", error);
      setErrorMsg(`Database error: ${error.message}`);
    } else {
      console.log("Supabase database success:", data);
      // 2. Redirect to the next specific onboarding page
      router.push('/onboarding/step-two'); 
    }
  };
}