"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { getTargetAreas, LEVEL_LABELS } from "@/lib/constants";
import { useAppStore } from "@/lib/store";
import type { WorkoutHistory, WorkoutPlan } from "@/lib/types";
import { SportHeader } from "@/components/dashboard/SportHeader";
import { TargetAreaSelector } from "@/components/dashboard/TargetAreaSelector";
import { WorkoutCard } from "@/components/dashboard/WorkoutCard";
import { WorkoutSkeleton } from "@/components/dashboard/WorkoutSkeleton";
import { RecentPlans } from "@/components/dashboard/RecentPlans";
import { Button } from "@/components/ui/Button";

export default function DashboardPage() {
  const router = useRouter();
  const profile = useAppStore((s) => s.profile);
  const onboarded = profile.onboarded;
  const selectedTargetAreas = useAppStore((s) => s.selectedTargetAreas);
  const toggleTargetArea = useAppStore((s) => s.toggleTargetArea);
  const setTargetAreas = useAppStore((s) => s.setTargetAreas);
  const currentPlan = useAppStore((s) => s.currentPlan);
  const setCurrentPlan = useAppStore((s) => s.setCurrentPlan);
  const addToHistory = useAppStore((s) => s.addToHistory);
  const workoutHistory = useAppStore((s) => s.workoutHistory);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hydrated, setHydrated] = useState(false);

  const sportId = profile.sport ?? "default";
  const areas = getTargetAreas(sportId);

  useEffect(() => {
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    if (!onboarded) router.replace("/onboarding");
  }, [hydrated, onboarded, router]);

  useEffect(() => {
    if (selectedTargetAreas.length === 0 && areas.length > 0) {
      setTargetAreas([areas[0], areas[1]].filter(Boolean));
    }
  }, [areas, selectedTargetAreas.length, setTargetAreas]);

  const generatePlan = useCallback(async () => {
    if (selectedTargetAreas.length === 0) {
      setError("Select at least one target area.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/generate-workout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sportId: profile.sport ?? "default",
          sport: profile.sportName ?? profile.sport,
          levelId: profile.level ?? "amateur",
          level: LEVEL_LABELS[profile.level ?? "amateur"] ?? profile.level,
          goals: profile.goals ?? [],
          targetAreas: selectedTargetAreas,
          trainingDays: profile.trainingDays,
          sessionDuration: profile.sessionDuration,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error ?? "Failed to generate plan");
      }

      const plan: WorkoutPlan = await res.json();
      setCurrentPlan(plan);

      const entry: WorkoutHistory = {
        id: crypto.randomUUID(),
        generatedAt: new Date().toISOString(),
        sport: profile.sportName ?? "Sport",
        targetAreas: selectedTargetAreas,
        plan,
      };
      addToHistory(entry);
    } catch {
      setError("Couldn't load your plan — try again.");
    } finally {
      setLoading(false);
    }
  }, [profile, selectedTargetAreas, setCurrentPlan, addToHistory]);

  const copyFullPlan = () => {
    if (!currentPlan) return;
    const lines = currentPlan.workouts.map(
      (w) =>
        `#${w.rank} ${w.name} (${w.effectiveness}/100 — ${w.rankLabel})`
    );
    const text = `${profile.sportEmoji} ${profile.sportName} Workout — ${LEVEL_LABELS[profile.level ?? "amateur"]}
━━━━━━━━━━━━━━━━━━━━━
${lines.join("\n")}
Generated by Athlete Workout Planner`;
    navigator.clipboard.writeText(text);
  };

  if (!hydrated || !onboarded) {
    return (
      <div className="flex min-h-dvh items-center justify-center">
        <div className="h-8 w-8 animate-pulse rounded-full bg-[var(--tint-light)]" />
      </div>
    );
  }

  return (
    <div className="min-h-dvh bg-[var(--bg-secondary)] pb-12">
      <div className="mx-auto max-w-[640px] px-5 py-8">
        <SportHeader
          firstName={profile.firstName ?? "Athlete"}
          sportEmoji={profile.sportEmoji ?? "🏋️"}
          sportName={profile.sportName ?? "Sport"}
          level={profile.level ?? "amateur"}
        />

        <div className="mt-8 space-y-8">
          <TargetAreaSelector
            areas={areas}
            selected={selectedTargetAreas}
            onToggle={toggleTargetArea}
          />

          <Button onClick={generatePlan} loading={loading} disabled={loading}>
            Generate Workout Plan
          </Button>

          {error && (
            <p className="text-center text-[15px] text-[var(--danger)]" role="alert">
              {error}
            </p>
          )}

          <RecentPlans history={workoutHistory} />

          {(loading || currentPlan) && (
            <section aria-label="Workout ranking">
              <div className="mb-4 flex items-center justify-between">
                <h2 className="text-[13px] font-semibold uppercase tracking-wide text-[var(--label-tertiary)]">
                  Your Workout Ranking
                </h2>
                {currentPlan && !loading && (
                  <button
                    type="button"
                    onClick={copyFullPlan}
                    className="text-[15px] font-medium text-[var(--tint)] focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--tint)]"
                  >
                    Copy all
                  </button>
                )}
              </div>
              <div className="mb-4 flex justify-between text-[12px] text-[var(--label-tertiary)]">
                <span>Worst</span>
                <span>Best</span>
              </div>

              {currentPlan?.summary && !loading && (
                <motion.p
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="mb-4 text-[15px] text-[var(--label-secondary)]"
                >
                  {currentPlan.summary}
                </motion.p>
              )}

              {loading ? (
                <WorkoutSkeleton />
              ) : (
                currentPlan && (
                  <div className="space-y-3">
                    {currentPlan.workouts.map((workout, i) => (
                      <WorkoutCard
                        key={workout.rank}
                        workout={workout}
                        index={i}
                        sportEmoji={profile.sportEmoji}
                        sportName={profile.sportName}
                        sportId={profile.sport}
                        levelLabel={LEVEL_LABELS[profile.level ?? "amateur"]}
                      />
                    ))}
                  </div>
                )
              )}
            </section>
          )}
        </div>
      </div>
    </div>
  );
}
